### ISSUE TITLE
Getting an error when trying to export a group

### ISSUE THREAD

**Issue by anadin** [Takanu/GEX#1]
Open default Blender scene, duplicate a cube, group the cubes and called the group 'Cubes' :)

Set the Location, add a Default Export Settings and then click 'Export' I get this error

"No name has been given to the Cubes group object, please give it a name."

OSX 10.11.2, Blender 2.76b

Longer log..

bpy.ops.group.create(name="Cubes")
bpy.context.scene.GXScn.object_switch = '2'
bpy.data.groups["Cubes"].GXGrp.export_group = True
bpy.data.groups["Cubes"].GXGrp.location_default = '0'
bpy.context.space_data.system_bookmarks_active = 3
bpy.context.scene.GXScn.location_defaults_index = 0
bpy.context.scene.GXScn.location_defaults[0].name = "Desktop"
bpy.context.scene.GXScn.engine_select = '2'
No name has been given to the Cubes group object, please give it a name.

**Comment by Takanu** [comment]
Thanks for the issue report and apologies for the delay in response. ~~I'll check it out :)~~ I've confirmed the bug and will fix it shortly :+1:

**Comment by Takanu** [comment]
Actually, although this is a planned feature, currently you need to define a Root for the object.  The error report was poorly worded and I apologise :/
