### ISSUE TITLE
Apply Modifires doesn't work in Capsule v1.1

### ISSUE THREAD

**Issue by kamilozo** [Takanu/GEX#10]
Hi.

I have some issue with Your plugin and I don't know how to fix it. 
I apply modifires in plugin menu and save setting, but this has no effect on exported model.
It is strange, because in older version everyhing is ok.

**Comment by Takanu** [comment]
Hey, thanks for reporting this to me but as the feature in it's current implementation in 1.1 no longer exists in the next version i'm working on, i'm going to close this for now 👍
