### ISSUE TITLE
UCX_ and _LODx doesn't work

### ISSUE THREAD

**Issue by ElFab** [Takanu/GEX#11]
Normaly when exporting an FBX file with the folowing meshes names :

- MeshName_LOD0
- MeshName_LOD1
- UCX_MeshName

With Blender FBX exporter, even when exporting as one file per Object, they will be grouped together in one file with Collision (UCX) and LODs you created. The capsule doesn't take into account this thing and that make it unusable with UE4.
For the LOD part it's not a real probleme because we can import LODs from different files so we can work with the current Capsule, but for UCX there is no other way than create theme in within UE4, because of that i don't know if i'll use capsule anymore but that's an awesome feature that all people should use and cannot see a world witout it...

Thank you for your work, Capsule is somthing very nice. Where can we found a topik or blog for speak about Capsule?

**Comment by Takanu** [comment]
Hey, thanks for the bug report but as this system will be changed radically in future releases i'm going to close this 👍
