### ISSUE TITLE
SubFolder Doesn't Work

### ISSUE THREAD

**Issue by ElFab** [Takanu/GEX#12]
We can work without this feature but i just wanted you to know that Capsule cannot create subFolder on my computer (maybe it work for other poeple and it's something i should setup i don't know).
I'm running Blender as administrator on win 10. 
This is appenning if a add a subfolder name or if i add a file suffix, same error occur in both case.
If i check the "Substitute invalide Folder Characters" option, nothing happen, not file or folder are created.
If i uncheck it then i got this error :
![error](https://user-images.githubusercontent.com/43233110/45475968-1ac87400-b73e-11e8-8d94-c6711832e79f.png)
I searched in files and the "CheckSystemChar" is where it should be, i tryed to make it return [] and the error popup anyway.

**Comment by Takanu** [comment]
Thanks for the issue and sorry it took me so long to get back to you - i'll keep an eye out for this as I work on the next release 👌

**Comment by Takanu** [comment]
This should no longer be an issue in 1.2, let me know if it happens during the beta.
