### ISSUE TITLE
Fails to export in latest Blender daily Builds

### ISSUE THREAD

**Issue by juangea** [Takanu/GEX#13]
Fails to export in latest Blender daily Builds

**Comment by kelheor** [comment]
Update this code export_operators.py:

def ExportFBX(self, filePath):
        # Calls the FBX Export API to make the export happen

        print("APPLY UNIT SCALE, IS IT FUCKING ON?", self.apply_unit_scale)

        print("Exporting", "*"*70)
        bpy.ops.export_scene.fbx(check_existing=False,
        filepath=filePath,
        filter_glob="*.fbx",
        use_selection=True,
        global_scale=self.global_scale,
        apply_unit_scale=self.apply_unit_scale,
        axis_forward=self.axisForward,
        axis_up=self.axisUp,
        bake_space_transform=self.bakeSpaceTransform,
        object_types=self.export_types,
        use_mesh_modifiers=self.applyModifiers,
        mesh_smooth_type=self.meshSmooth,
        use_mesh_edges=self.loose_edges,
        use_tspace=self.tangent_space,
        use_custom_props=False,
        use_armature_deform_only=self.use_armature_deform_only,
        add_leaf_bones=self.add_leaf_bones,
        bake_anim=self.exportAnim,
        bake_anim_use_all_bones=self.bake_anim_use_all_bones,
        bake_anim_use_nla_strips=self.bake_anim_use_nla_strips,
        bake_anim_use_all_actions=self.bake_anim_use_all_actions,
        bake_anim_force_startend_keying=self.bake_anim_force_startend_keying,
        path_mode=self.batch_mode,
        embed_textures=True,
        batch_mode='OFF',
        use_batch_own_dir=False,
        use_metadata=False)

        self.exportedFiles += 1

Looks like FBX export API was changed a little

**Comment by Takanu** [comment]
The FBX export API has indeed changed since 2.79.

This is something i've since fixed in the new version i'm developing but I don't recommend you use the latest source code unless you're really curious as i've yet to fully update and test it.
