### ISSUE TITLE
Blender 2.8 support

### ISSUE THREAD

**Issue by kelheor** [Takanu/GEX#14]
Any chances to update your plugin to support Blender 2.8?
Your plugin is a big must have for environment development in Blender and without it really hard to normally work in 2.8.

**Comment by juangea** [comment]
Agree, now that we are in Beta and that the Python API is stabilized, could be great to have this working over 2.8 already, we shifted practically all our work to 2.8, it´s a pity to not being able to use Capsule in 2.8

Cheers!

**Comment by nspidel** [comment]
Any word? I've been using Blender 2.8 primarily since September, and I really could use this functionality for my job. I'd be willing to buy this for $80 minimum on your Gumroad if this addon can integrate nicely with my UE4 workflow.

**Comment by CarpgianeDS** [comment]
Hey. I'd also be willing to pay a fee for this because it'll be a great improvement in my daily workflow I have sent you and email with some suggestions. Thanks

**Comment by Takanu** [comment]
Hey, sorry for not responding (i actually didn't realise people were posting issues and I wasn't getting notifications).

It will take a while but i'm currently working on a 2.8 compatible version.  If you didn't see the Gumroad email I sent yesterday it will also be a thoroughly redesigned version of the addon.  It'll take longer but I still hope to have it out by the release of 2.8.

**Comment by Takanu** [comment]
I'm still working out some bugs and adjustments for 2.8 but this is complete.  The code in the master branch I still don't recommend using but I should have a 1.2 beta out soon.

**Comment by idchlife** [comment]
@Takanu what's the news on 2.8 support?

**Comment by Takanu** [comment]
@idchlife It works, check out the Releases tab for 1.20 beta.
