### ISSUE TITLE
Export presets not saved in 2.8.2

### ISSUE THREAD

**Issue by ILIOSIN** [Takanu/GEX#19]
When we save export preset setting, we can't apply this in another file, it's gone from saved presets.
Blender 2.8.2 - 2.9

But we can use old preset with  files saved with old version on new blender version

**Comment by ILIOSIN** [comment]
Solution is replace NDOF_TRANS to another value.. for example CHECKBOX_HLT
on line 327 in export_format_fbx.py

**Comment by Takanu** [comment]
Sounds like this is because I haven't updated my export definitions for the new version of Blender - they change slightly between versions and I haven't been keeping up recently 🙈 .

I'll look into it now I'm using Blender again and see what needs to be updated.
