### ISSUE TITLE
Unable to export animations to Unity 5

### ISSUE THREAD

**Issue by local306** [Takanu/GEX#2]
Hey,

I'm currently using Capsule 1.06 and I haven't had any luck exporting animations to Unity. I've setup actions for different animations in the dope sheet. When I import into Unity it shows there is no animation data associated with my export...

**Comment by Takanu** [comment]
Hey there!  

So long as the animation is attached to an armature, it "should" export just fine so long as you have actions for it.  I will check this during the update and reply back if fixed or if I found anything that currently stops me from making it work.
