### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by vyorkin** [Takanu/GEX#20]
Hello @Takanu!

I've just installed the plugin but got the following error after clicking on the "Create capsule data" button:

![image](https://user-images.githubusercontent.com/988849/83359556-9a1f3080-a383-11ea-8325-2072648e7af7.png)

**Comment by Takanu** [comment]
Hey there, did you try to enable it while in Edit Mode?  I feel like I should have written a failsafe for this but I might not have 🙊

**Comment by vyorkin** [comment]
Hey, Takanu! I'm not sure... I'll check it again in both modes and provide some more feedback soon

**Comment by Takanu** [comment]
Thanks @vyorkin .  If this did work for you let me know :)

**Comment by Takanu** [comment]
I'm pretty sure this is due to a lack of object selections in the viewport, will close when I think i've fixed it but if more information could be provided that would be awesome 👍
