### ISSUE TITLE
Export groups and parents with all object inherited but not singularly

### ISSUE THREAD

**Issue by fpibbs** [Takanu/GEX#21]
I'd love to understand if the plugin can fulfil this need: 

export groups and parents/children but not singularly (I have 215 groups and 1600 objects inherited): the scope is to have 215 fbx with the 3d objects inherited inside divided by group, parenting.
Hope it's possible

**Comment by Takanu** [comment]
Hey there, thanks for the feedback (sorry it's taken so long for me to reply!).  Could you explain the issue you're having in more detail?
