### ISSUE TITLE
Extension doesn't show up in extension list

### ISSUE THREAD

**Issue by Shadowblitz16** [Takanu/GEX#22]
This doesn't show up in the extension list unless I extract and zip the sub Capsule folder and use that.
however then the Capsule menu under view doesn't have anything there

![image](https://user-images.githubusercontent.com/2453707/93271021-299bf400-f767-11ea-9aea-1bb1901d62fb.png)

**Comment by magicjar** [comment]
You need to create Capsule Data first.

Open Capsule add-on preference > Create Capsule Data.

**Comment by Shadowblitz16** [comment]
there should be documentation on in the readme then on how to use it.
