### ISSUE TITLE
Lag with export list

### ISSUE THREAD

**Issue by ILIOSIN** [Takanu/GEX#23]
Hi, when this Export list is open, interface is too laggy, CPU use is up. When i roll up Export list tab, it's ok again.

I have just 5 collection for export and no objects,  on objects tab when is empty it works fine too
In another scene with one collection in this tab, it also works fine
![image](https://user-images.githubusercontent.com/36762474/110912352-e3de7380-8324-11eb-81da-b094a466b85c.png)
![image](https://user-images.githubusercontent.com/36762474/110912568-2607b500-8325-11eb-83c7-b228c871663f.png)

**Comment by Takanu** [comment]
Thanks for reporting this issue, I've never experienced the interface being laggy when this panel is open but ill look into it and get back to you if I need more information.

**Comment by Takanu** [comment]
So I did some initial tests with a bigger scene and I was unable to find any performance issues you mentioned.  Can you send me a test .blend file where this problem occurs?

**Comment by Takanu** [comment]
Nevermind, I found it and am finalizing a fix.  Will be fixed in 1.3.
