### ISSUE TITLE
Can't enable Capsule after install

### ISSUE THREAD

**Issue by guategeek** [Takanu/GEX#24]
Just installed your plugin v1.3 and I can't enable it (clicking the checkbox), this is in Blender 2.92.0. I get the following error:

![image](https://user-images.githubusercontent.com/868801/111215720-1395b180-8599-11eb-898a-4b7ddd2437d3.png)

**Comment by guategeek** [comment]
I was able to get the plugin to load by renaming the directory from `Capsule-1.3` to `Capsule` in my:

C:\Users\ **USERNAME** \AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons

--

If you download the plugin from the Gumroad rather than here on the GitHub release page, then everything is named correctly and it works.

**Comment by Takanu** [comment]
Hey, this is an issue with the naming of the ZIP file - Blender wont accept dots in ZIP file names.  I made a bad assumption in thinking GitHub zips would avoid this.

Ill add instructions telling people to rename the ZIP file before installing, thanks for pointing this out!

**Comment by Takanu** [comment]
Turns out GitHub changes the folder name inside the ZIP too - I changed the way files are organized and the installation instructions 👍
