### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name' on Collection export

### ISSUE THREAD

**Issue by Flynsarmy** [Takanu/GEX#28]
Exporting Objects works fine but when clicking Export All on the Collections tab I get the following error:

> Python: Traceback (most recent call last):
>   File "path\to\Blender\2.93\scripts\addons\Capsule\export_operators.py", line 107, in execute
>     collection_export_result = ExportCollectionList(context, exp, export_collections, global_record)
>   File "path\to\Blender\2.93\scripts\addons\Capsule\export_operators.py", line 354, in ExportCollectionList
>     root_definition = bpy.context.scene.objects.get(collection.CAPCol.root_object.name)
> AttributeError: 'NoneType' object has no attribute 'name'
> 
> location: <unknown location>:-1

![image](https://user-images.githubusercontent.com/334808/126745364-91ff24d3-71aa-40e3-ba92-8804f7801dc5.png)

Capsule version 1.3.0 with pretty much default Preferences settings:
![image](https://user-images.githubusercontent.com/334808/126745486-70fb2c85-e124-4bc4-8046-f7790a189fe3.png)

**Comment by Takanu** [comment]
Hey, thanks for reporting this.  I don't have any immediate solutions or ideas but I'll look into this when I can and see what I can find 👌

**Comment by Takanu** [comment]
I've been able to confirm this issue as I prepare a bugfix release and it should be fixed with 1.4.
