### ISSUE TITLE
Apply modifier stack but not shape keys

### ISSUE THREAD

**Issue by SkaveRat** [Takanu/GEX#3]
Something I'm missing from every export helper out there, is a feature to export a skeletal mesh with the modifier stack applied, but shapekeys intact.

"apply modifiers" removes shape keys, which is really not useful if you need them in UE4.

Currently you need to copy the object, apply the stack manually and then export the copy. Very tedious and error-prone if you export often.

**Comment by Takanu** [comment]
It doesn't sound like too much of a problem to solve, but as always there could be some unexpected things that prevent this from being a possibility.

I'll look into it for the upcoming update, but I can't promise anything - if it doesn't get added this version then I will certainly include it for consideration in a future version as this clearly seems important 👍
