### ISSUE TITLE
Blendshape support

### ISSUE THREAD

**Issue by indianaj0nas** [Takanu/GEX#30]
Hello,

I'm trying to export some blend shapes to Unity in an FBX. But it doesn't seem to be included in the export. There doesn't seem to be any options for it either.

Do you know any workaround or do you have any plans to add it?

**Comment by Takanu** [comment]
If FBX supports blendshapes then Capsule should as well, i'm currently working on an API update and bugfix version for 3.1 so i'll investigate this and see whats up as i'd be surprised if Blendshapes weren't supported by the file format 🙊 .

**Comment by Takanu** [comment]
Hey, after working on some bug fixes it appears that for FBX and GLTF export file types you can't use Apply Modifiers in order to get this kind of data to export.  Are you able to confirm this?
