### ISSUE TITLE
addon not showing

### ISSUE THREAD

**Issue by Willie2020** [Takanu/GEX#32]
Hi, after installing the addon, it doesn't show in the addons list

**Comment by Takanu** [comment]
Hey, did you install it by first unzipping the release folder?  You need to do the following to install it properly:
- Unzip the archive you receive when you download Capsule
- Open the folder and ZIP the Capsule folder contained inside (ensure there are no spaces or special characters in the name).
- Use this ZIP when installing a new addon.

Let me know what happens 👌
