### ISSUE TITLE
Mac file path error: The File Location points to a file rather than a directory.

### ISSUE THREAD

**Issue by jrockett6** [Takanu/GEX#36]
On Mac, Blender 3.2.1, when trying to export I get:`The File Location 'Location 1' points to a file rather than a directory.  Please ensure it points to a folder.` Despite the location specified for 'Location 1' being a directory.

**Comment by Takanu** [comment]
Thanks a lot for the bug report and sorry I haven't responded sooner - this is pretty important and I'll create a fix for this as soon as I can.

**Comment by Takanu** [comment]
Hey, can you test to see if this works on 3.3?

Additionally, can you tell me if the path you're using is Relative?  (check the tickbox when selecting a file path to see whether it's on or not).
![image](https://user-images.githubusercontent.com/9108903/188929694-228ec63d-5b06-4540-a4e9-8190888fb656.png)

Thanks!

**Comment by Takanu** [comment]
I reckon I was able to replicate this, Relative Paths can cause errors when file structures change and the warning Capsule gave needed to be more specific.  This has changed in the latest commit so I'm now closing this, let me know if you still have this issue and ill do some more digging.
