### ISSUE TITLE
New FBX export option in 2.79

### ISSUE THREAD

**Issue by pietruh00s** [Takanu/GEX#4]
Hi, there is problem with scaling when exporting. Current Blender version 2.79 has option named "Apply Scale". When set to default "All Local" causes scale multipilied by 100 in Unity (file scale set to 0,01). To fix this we need to set apply scale to any option with "FBX...". So please add support for this option. :)
  
![zrzut ekranu 2017-10-13 o 10 55 15](https://user-images.githubusercontent.com/11031197/31538183-0a9844f2-b005-11e7-8b83-820357225d95.png)

Unity Import Settings after export from Capsule:
![zrzut ekranu 2017-10-13 o 11 01 15](https://user-images.githubusercontent.com/11031197/31538453-e4018f96-b005-11e7-8dec-66a9a6de13d6.png)

**Comment by Takanu** [comment]
Thanks for the report, i'll get this option included in the Export Presets for the upcoming version :)

**Comment by Takanu** [comment]
This has been added to the development version of Capsule 1.1, thanks for letting me know.
