### ISSUE TITLE
Export armature with mesh?

### ISSUE THREAD

**Issue by Flynsarmy** [Takanu/GEX#43]
Is it possible to export an armature with its child mesh(s) as a single file? For example Here is a bus I've attached a simple armature to:
![image](https://user-images.githubusercontent.com/334808/220512340-cd6dd682-3f10-4420-97d7-71eed1cfd429.png)

If I select the armature, only the armature exports. If I select both the armature and its child mesh, they export as separate files:
![image](https://user-images.githubusercontent.com/334808/220512569-656bff94-cd3f-4b6f-8b29-66d7b7c953e6.png)

**Comment by Takanu** [comment]
Hey, if you want an object with child meshes to export you'll need to use the Collection export instead of the Object export option.  You can see in the Capsule menu in the 3D View that you can change between the settings for a selected Object and a selected Collection.
