### ISSUE TITLE
keyword 'scaling_factor' unrecognized

### ISSUE THREAD

**Issue by Flynsarmy** [Takanu/GEX#44]
Blender 3.4.1. When I attempt to export OBJ I get the following error:
![error](https://user-images.githubusercontent.com/334808/220519205-a2cbf51e-8393-492d-86c4-c4cd8a16575d.png)
Settings for export are the default OBJ settings in the export presets section.

**Comment by Takanu** [comment]
Hey, it looks like there's a property in the OBJ exporter that changed and I didn't catch it for the 3.4 release.  I'll make this a priority for the next update but trying 3.4.0 might fix it if it occured during the last patch (of course there's always a chance that I missed this in my testing, sorry about that 😅).

**Comment by Flynsarmy** [comment]
All good and thanks for the hard work. Love the addon. It really makes life so much easier!

**Comment by Takanu** [comment]
Thanks again for the bug report, it's been fixed and a new version will be released soon.
