### ISSUE TITLE
Can't remove Active Export Presets

### ISSUE THREAD

**Issue by guategeek** [Takanu/GEX#45]
I was trying out different export pressets, testing some things and now I have a bunch that I don't want any more. But in the preferences when I select a preset from "Active Export Presets" and click the "-" button nothing happens, they are not removed from the list.

Again I just wanted to say how much I love this add-on, it is SO useful and saves me tons of time. Especially love how you can set up exports on collections and limit depth of children, and the quick pie menu. Thanks for the work you put into it and for sharing it with us.

**Comment by Takanu** [comment]
Hey, thanks for the post!  I'll look into this as I update the addon for Blender 3.5.

**Comment by Takanu** [comment]
Sorry for the long wait, this should be fixed in the upcoming version for Blender 3.5 (03ab9395e86a593c7d754c4a4832c7e4ebfca99c)
