### ISSUE TITLE
Add an option to cleanup all Capsule data from scene 

### ISSUE THREAD

**Issue by Ali-RS** [Takanu/GEX#47]
Hi,

Can you please add an option in the panel to clean up all the Capsul-added data from the scene as well as all the "custom properties" added by the addon?

Thanks

**Comment by Takanu** [comment]
Hey there, this should be possible by going to the Addon Preferences > Extra Settings > Reset Capsule Scene Data.  Let me know if this works 👍

**Comment by Ali-RS** [comment]
>this should be possible by going to the Addon Preferences > Extra Settings > Reset Capsule Scene Data. Let me know if this works

Seem that option does not work for me. Nothing happens when I click it and I still see the custom properties added by the Capsule addon get exported into gltf file when I export the object directly with the blender gltf io addon.

I am using Blender 3.4.1 and Linux Mint.

**Comment by Takanu** [comment]
Apologies for the delay, I wanted to be able to address this when I had the time to update the plugin for Blender 3.5.

I was mistaken in thinking this function would remove the properties, the addon registers a block of properties to every object when the addon is activated and it's necessary in order for Capsule to function as a Blender addon.  The only way to remove them is to disable Capsule.

Sorry I can't fix this particular workflow issue for you right now, hopefully GLTF or a Blender python feature in the future might be able to fix this.
