### ISSUE TITLE
some bug when 3.6

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [Takanu/GEX#48]
It will write in log when starting the blender 3.6

```
Traceback (most recent call last):
  File "G:\blenderplus\3.0\addons\Capsule\__init__.py", line 449, in CheckSelectedObject
    if bpy.context.active_object is not None:
AttributeError: 'Context' object has no attribute 'active_object'
```

And then
Do you have time to finish the wiki of this addon when you have free time
So you'd better hide it, because until now it had nothing ...
<a href="https://emoji.gg/emoji/6027-lmaocry"><img src="https://cdn3.emoji.gg/emojis/6027-lmaocry.png" width="64px" height="64px" alt="lmaocry"></a>

**Comment by Takanu** [comment]
Hey, the addon isnt compatible with Blender 3.6 yet, I dont release compatibility updates until the next version is out.  Ive only verified it to be compatible with 3.4 with a 3.5 update coming out soon.

The wiki does actually have pages, you just need to look at the sidebar.  I should really make the homepage of it look like something though, i understand the confusion 🙊
