### ISSUE TITLE
Filtering in Export List

### ISSUE THREAD

**Issue by Wolfgang-IX** [Takanu/GEX#49]
Hi would be amazing if Export List has filtering like Vertex Group if possible 😊
like Searching and Invert Search, for disabling/enabling objects/collections for export

![image](https://github.com/Takanu/Capsule/assets/47208316/8c0cb92e-100e-411f-aebe-4bab00b76644)

**Comment by Takanu** [comment]
Hey, i'm not quite sure what the filtering aspect you want applies to - do you want to search exports by vertex groups or do you want to prevent certain vertex groups from being updated?

**Comment by Wolfgang-IX** [comment]
Oh I mean searching the list in Export List panel, in that example I have 98 collections to be exported but I want to disable/enable some of them before exporting all active list.

so what I propose is searching tab below it like you can found on Vertex Group, UV Map etc.

![image](https://github.com/Takanu/Capsule/assets/47208316/7b97fb0f-6fa9-43da-8d1f-a6529c1ec6fc)

**Comment by Takanu** [comment]
Oh, now I understand!  I'll see if I can smuggle this in before publishing the next update 👍

**Comment by Takanu** [comment]
This has now been added and will be released in the next version, thanks for reminding me about this issue!

Btw, is that a custom interface you have for Capsule?  I'm curious 🤔 .

**Comment by Wolfgang-IX** [comment]
Thank you so much, it'll be easier to find stuffs now 😊

Yup I'm customizing it with PME (Pie Menu Editor).

https://github.com/Takanu/Capsule/assets/47208316/536fa7e8-9ccd-451e-b68d-20dbe80a6673

**Comment by Takanu** [comment]
Aaah, interesting addon!  A shortcut to go to the Capsule Addon Preferences was added with the upcoming version amusingly enough so hopefully that makes your custom setup a little less complicated.
