### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by benvoldman** [Takanu/GEX#51]
Error on addon install - " no module named: Capsule -1"

**Comment by benvoldman** [comment]
![image](https://github.com/Takanu/Capsule/assets/105070180/34e72840-9008-4ad4-8778-495107a614cc)

**Comment by Wolfgang-IX** [comment]
it's folder naming issue, rename it when it's in .zip or in `...\AppData\Roaming\Blender Foundation\Blender\[Version]\scripts\addons\`
to just **Capsule** 
![image](https://github.com/Takanu/Capsule/assets/47208316/1ce57186-ba3f-41f8-bd1c-f33d5164d376)

**Comment by benvoldman** [comment]
Perfect! Thank you. Love this addon:)

**Comment by Takanu** [comment]
I forgot to add this to the instructions 🙈.  I'll have this done on a bit.
