### ISSUE TITLE
Capsule export errors (won't complete exporting)

### ISSUE THREAD

**Issue by guategeek** [Takanu/GEX#52]
Capsule will work if I set it up on a new file, with new objects. 

But my previous files always throw an error "The selected object(s) require a Location Preset to be defined - check the Export Lists to see all missing properties." when I try to export with capsule. 

Its a drag because I had 100s of objects set up for export, some as objects and others using collections. I have come to really depend on this add-on.

I then tested a new file, gotten it to export a new object fine, and then pasted or append (both methods same result) an object from a file that won't export. It immediately throws the same error. The weird thing is now the object that exported with capsule before no longer exports and I get the same error. Any help would be appreciated, as I love how capsule works it makes life so much easier.

**Comment by Takanu** [comment]
Hey, while I dont currently have a computer to be able to check this, im 99% sure this was because of recent changes in the export property names.

My guess is the new version of Capsule isnt recognizing the old property names for things like location presets.  I can't offer a solution right now (not without a computer anyhow), and while I cant promise a fix i will look into one when I have a computer to work on.

**Comment by guategeek** [comment]
Thanks, if you do find a way to fix this, or simply clean the file of all old property names so I can set it all up again that would be helpful.

**Comment by Wolfgang-IX** [comment]
that's weird i didn't have issue from the one i made on 1.37 with 1.40 i can export on that file, append it on new file, every settings is there and works with >50 collections.
tho i use it for collection not object.

if i were you i'll just redo it 😅, to make things faster you could make macro out of it like i [did](https://github.com/Takanu/Capsule/issues/49#issuecomment-1547293263) using PME (pie menu editor)
alternatively you can try [Action Recorder](https://github.com/InamuraJIN/ActionRecorder)

**Comment by guategeek** [comment]
Well I spent some time playing with my file today. Deleted the capsule data, saved and then reopened and set Capsule up again. It then complained that 5 collections were missing the Export Location, I went through my collections and found them. First I tried adding an export location to them but no settings would save, so I made new collections and moved the contents to those. Now capsule works again on the file. I went back to the previous file and was able to find those collections and replace them and now the old file works with all the previously set up exports. Not sure why the error changed but it helped me get my file working again!

**Comment by Takanu** [comment]
I'm really sorry for the trouble this caused you.  I'm going to close this for now as it's been a while since the version change happened, but if I have to change property names that relate to people's file settings in a future update I will do my best to ensure these are correctly preserved.
