### ISSUE TITLE
Error when installing 1.40 in an environment using 1.37

### ISSUE THREAD

**Issue by hjaki** [Takanu/GEX#53]
![error](https://github.com/Takanu/Capsule/assets/8922026/a04102d3-2804-48e3-9799-bd95cc196886)

Using 1.37 with Blender 3.5

Error pattern
- Uninstalling 1.37 with Blender 3.5
- Uninstall 1.37 after "Load 3.5 Setting" in Blender 3.6

Patterns without error
- "Save New Setting" in Blender 3.6
- Uninstall 1.37 in Blender 3.5 and "Load 3.5 Setting" in Blender 3.6

**Comment by Takanu** [comment]
I'm going to close this for now as this is an error created as a result of some property changes between versions.  

While I should have implemented something so people's settings seamlessly move between versions, given that the change happened a while ago I don't think it's worth the limited time I have to solve this time.  If I have to change property names in a future version this will be accounted for.
