### ISSUE TITLE
Embed Texture option in FBX dose not work

### ISSUE THREAD

**Issue by hjaki** [Takanu/GEX#56]
To use Embed Texture, Path Mode must be set to Copy, but it appears that Absolute is specified.
I tried changing the value of "path_mode" in line 290 of "export_format_fbx.py" to 'COPY' and it worked correctly.

I use Blender 3.6.8

**Comment by Takanu** [comment]
Hey, thanks for catching this error!  I cant fix it right now as I don't have access to my laptop but ill fix this when I am able.

**Comment by Takanu** [comment]
Fixed!  This will be in version 1.4.1.
