### ISSUE TITLE
Created a YT Video showing how useful this is for Game Developers.

### ISSUE THREAD

**Issue by ghost** [Takanu/GEX#9]
Sorry I did not know any other way to get in contact with you. This is not an "Issue" so feel free to delete it.

Personally I find your plugin to be the absolute most useful plugin for Game developers using Blender. I created a very indepth Youtube video showing how you can use your plugin to export whole scenes for game development using blender. 

In the video I show how to export with Collision and LODS using your Capsule plugin, As far as I know, no one has ever demonstrated this in blender using any plugin, ( Since it takes some code changes to the Import / Export plugin in blender "Did at the time of posting" ) so I though I might share it with you and you may find some use for it for your users. 

Also, now the import / export plugin for blender has been updated to work flawlessly out of the box with the method I show in the video using your capsule plugin for exporting LODS to UE4.

I hope you continue to work on this plugin as it is extremely useful to a large group of people who are not yet aware of its amazing capabilities. Great job and thank you very much.

Here is the video link, I hope you find some use for it for your users / possible users : https://www.youtube.com/watch?v=zFo0Bv5evM0&lc=UgxN_QUt1Gs1Ic8vHIt4AaABAg

Best Regards,
Kyle

**Comment by Takanu** [comment]
Sorry for not responding sooner, thanks for the video :)
